-- Create the history table
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action_type text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table history enable row level security;

-- Create policies
create policy "Users can see their own history" on history for select using (auth.uid() = user_id);
create policy "Users can insert their own history" on history for insert with check (auth.uid() = user_id);

-- Create the clients table
create table clients (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, name)
);

-- Enable Row Level Security for clients
alter table clients enable row level security;

-- Create policies for clients
create policy "Users can see their own clients" on clients for select using (auth.uid() = user_id);
create policy "Users can insert their own clients" on clients for insert with check (auth.uid() = user_id);
create policy "Users can update their own clients" on clients for update using (auth.uid() = user_id);
create policy "Users can delete their own clients" on clients for delete using (auth.uid() = user_id);

-- Create the statements table
create table statements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  client_id bigint references clients(id) on delete cascade not null,
  file_name text not null,
  file_url text,
  transactions jsonb not null,
  summary jsonb,
  statement_month integer not null,
  statement_year integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, client_id, statement_month, statement_year)
);

-- Enable Row Level Security for statements
alter table statements enable row level security;

-- Create policies for statements
create policy "Users can see their own statements" on statements for select using (auth.uid() = user_id);
create policy "Users can insert their own statements" on statements for insert with check (auth.uid() = user_id);
create policy "Users can update their own statements" on statements for update using (auth.uid() = user_id);
create policy "Users can delete their own statements" on statements for delete using (auth.uid() = user_id);